### PR TITLE
Tests & Portable Artifacts

### PR DESCRIPTION
**Pull request by robyeates**
Hey Vorso, I mentioned on Twitter that I could create some Tests for this neat project - https://twitter.com/vorsomusic/status/1347834744776626181

To make it easier for people to use your software I created some zero-dependency artifacts using Packr. 

The code was of great quality. I moved some stuff around to make it easier to test. The operation is still the same. 

I added some tests and a License. The License is to make sure more people can use your project, counter-intuitive and explained better here  - https://medium.com/glitch/why-add-a-license-to-your-open-source-project-6f07941f9288

Let me know what you think! Hope you find this useful :)

### CODE REVIEW

**Comment by vorso** [comment]
Hi Rob,
First of all - amazing work! This is much better structured, the main is so much more legible now. The addition of tests is great as well. Licensing is a really good point, I didn't realise that not including a license defaults to all rights reserved so that article has been really helpful. I have another open source project I'll add a licence to asap.

I pulled the new code and tried running the extracted exe from the win64 directory and it looks like it hits this error after selecting an Ableton file:

`Exception in thread "main" javax.xml.parsers.FactoryConfigurationError: Provider com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderFactoryImpl not found
        at javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:200)
        at javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:152)
        at javax.xml.parsers.FactoryFinder.find(FactoryFinder.java:277)
        at javax.xml.parsers.DocumentBuilderFactory.newInstance(DocumentBuilderFactory.java:120)
        at org.apache.logging.log4j.core.config.xml.XmlConfiguration.newDocumentBuilder(XmlConfiguration.java:191)
        at org.apache.logging.log4j.core.config.xml.XmlConfiguration.<init>(XmlConfiguration.java:92)
        at org.apache.logging.log4j.core.config.xml.XmlConfigurationFactory.getConfiguration(XmlConfigurationFactory.java:46)
        at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:454)
        at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:386)
        at org.apache.logging.log4j.core.config.ConfigurationFactory.getConfiguration(ConfigurationFactory.java:261)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:616)
        at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:637)
        at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:231)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:153)
        at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
        at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
        at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:581)
        at com.vorso.filehandling.FileExtractor.<clinit>(FileExtractor.java:16)
        at com.vorso.TrackNameEditor.convertFiles(TrackNameEditor.java:104)
        at com.vorso.TrackNameEditor.main(TrackNameEditor.java:81)
Caused by: java.lang.ClassNotFoundException: com/sun/org/apache/xerces/internal/jaxp/DocumentBuilderFactoryImpl
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at javax.xml.parsers.FactoryFinder.getProviderClass(FactoryFinder.java:124)
        at javax.xml.parsers.FactoryFinder.newInstance(FactoryFinder.java:188)
        ... 19 more`

Which looks like a missing package... is there an Maven install I need to do first to run? Let me know if I've missed a step in running this and I'll merge this in.

Again, thank you so much, really appreciate what you've done here!

**Comment by robyeates** [comment]
Hey Vorso,

Glad you found the contribution useful! I'll replicate and fix the issue you are seeing and provide an update :)

**Comment by robyeates** [comment]
The issue is caused by the minification via [packr](https://github.com/libgdx/packr). I'm looking into some alternative packaging approaches which will resolve this. 

Removing the `"minimizejre": "hard",` option in Packr more than doubles the output size to ~100MB which seems far too big!

Moved to logback instead of log4j2 and updated the `readme` to reflect current instructions.

Let me know what you think :)

**Comment by vorso** [comment]
Yep that fixes the problem! 

Running using "java -jar target/ableton-track-name-editor-0.jar" runs fine in command prompt but it seems like it prints the ANSI colours as strings rather than interpreting them as colours. Seems like running using maven mvn exec:java -Dexec.mainClass="com.vorso.TrackNameEditor" shows the colours correctly, not sure if this is a command prompt specific thing?

It looks like the scanner gets closed early so the final scanner.nextLine hits an error but that's should be a really easy fix which I'll do after merging.

Again, thanks so much for your work on this, learnt a few tricks from reading through the code. Been looking for a good way to make the file picker look more modern for a while now!

**Comment by robyeates** [comment]
Thanks so much 👍 This was really fun to work on. 

Bit busy now for a while with IRL stuff. In my spare time I'll be playing with [this new UI framework](https://github.com/JetBrains/compose-jb) which also solves the cross-platform packaging issues. 

Keep creating these super useful tools! Maybe we could work together again to bring them into a single UI at some point in the future 🚀 🚀

**Pull request merged**
